// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBF3XAzz5tJBWCYY4ihNC6qYgYg0vjbOBU',
    appId: '1:394656564898:web:512eaf8c4af81307c579fb',
    messagingSenderId: '394656564898',
    projectId: 'expensetraking-9d192',
    authDomain: 'expensetraking-9d192.firebaseapp.com',
    storageBucket: 'expensetraking-9d192.firebasestorage.app',
    measurementId: 'G-Y1MC1QFM8P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAoxJ1S_j0UuKWo0H0lgSJMDJgD_VKbIo',
    appId: '1:394656564898:android:61b47cc39f5949b5c579fb',
    messagingSenderId: '394656564898',
    projectId: 'expensetraking-9d192',
    storageBucket: 'expensetraking-9d192.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZJ6E0FaYM9bFgxT470PHeIn4XDc4GpwU',
    appId: '1:394656564898:ios:c141bebd582ab833c579fb',
    messagingSenderId: '394656564898',
    projectId: 'expensetraking-9d192',
    storageBucket: 'expensetraking-9d192.firebasestorage.app',
    iosBundleId: 'com.example.expeTraking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZJ6E0FaYM9bFgxT470PHeIn4XDc4GpwU',
    appId: '1:394656564898:ios:c141bebd582ab833c579fb',
    messagingSenderId: '394656564898',
    projectId: 'expensetraking-9d192',
    storageBucket: 'expensetraking-9d192.firebasestorage.app',
    iosBundleId: 'com.example.expeTraking',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBF3XAzz5tJBWCYY4ihNC6qYgYg0vjbOBU',
    appId: '1:394656564898:web:1c9d525eff4b83d5c579fb',
    messagingSenderId: '394656564898',
    projectId: 'expensetraking-9d192',
    authDomain: 'expensetraking-9d192.firebaseapp.com',
    storageBucket: 'expensetraking-9d192.firebasestorage.app',
    measurementId: 'G-6GPEDCM11Y',
  );

}